# Generated by Django 4.1.6 on 2024-05-17 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test only auth name claim', max_length=200)),
                ('sub', models.CharField(help_text='Test only auth sub claim', max_length=200)),
                ('group', models.TextField(choices=[('Exp', 'Exp'), ('Waitlist', 'Waitlist')], default='Exp')),
                ('currentDay', models.FloatField(default=1, help_text='User task progress - note that this number might be a float')),
                ('startDate', models.DateField(blank=True, help_text='Experiment start date', null=True)),
                ('banFlag', models.BooleanField(default=False, help_text='This field is managed by automatic rules which cannot be changed by admin')),
                ('feedback4', models.TextField(blank=True, null=True)),
                ('feedbackDay4Viewed', models.BooleanField(default=False, help_text='Auto set to true when user views feedback')),
                ('feedback5', models.TextField(blank=True, null=True)),
                ('feedbackDay5Viewed', models.BooleanField(default=False, help_text='Auto set to true when user views feedback')),
                ('feedback6', models.TextField(blank=True, null=True)),
                ('feedbackDay6Viewed', models.BooleanField(default=False, help_text='Auto set to true when user views feedback')),
                ('feedback8', models.TextField(blank=True, null=True)),
                ('feedbackDay8Viewed', models.BooleanField(default=False, help_text='Auto set to true when user views feedback')),
                ('user', models.OneToOneField(help_text='Auth user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
