# Generated by Django 4.1.6 on 2024-05-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webuser',
            old_name='feedbackDay4Viewed',
            new_name='feedback4Viewed',
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='feedbackDay5Viewed',
            new_name='feedback5Viewed',
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='feedbackDay6Viewed',
            new_name='feedback6Viewed',
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='feedbackDay8Viewed',
            new_name='feedback8Viewed',
        ),
    ]
